CREATE TABLE owners (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   first_name VARCHAR(150) NOT NULL,
   last_name VARCHAR(150) NOT NULL,
   date_of_birth date NOT NULL,
   email VARCHAR(450) NOT NULL,
   date_time_created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   date_time_updated TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   CONSTRAINT pk_owners PRIMARY KEY (id),
   CONSTRAINT uc_owners_email UNIQUE (email)
);