CREATE TABLE markings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   owner_entity_id BIGINT,
   name VARCHAR(400) NOT NULL,
   description VARCHAR(400) NOT NULL,
   date_time_invite_initial TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   date_time_invite_final TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   date_time_created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   date_time_updated TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   CONSTRAINT pk_markings PRIMARY KEY (id)
);

CREATE TABLE markings_invites (
  marking_entity_id BIGINT NOT NULL,
   invites_id BIGINT NOT NULL
);

ALTER TABLE markings ADD CONSTRAINT FK_MARKINGS_ON_OWNERENTITY FOREIGN KEY (owner_entity_id) REFERENCES owners (id);

ALTER TABLE markings_invites ADD CONSTRAINT fk_marinv_on_marking_entity FOREIGN KEY (marking_entity_id) REFERENCES markings (id);

ALTER TABLE markings_invites ADD CONSTRAINT fk_marinv_on_owner_entity FOREIGN KEY (invites_id) REFERENCES owners (id);